config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('we-bought-again/', include('we_bought_again.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

we_bought_again/urls.py
from django.urls import path

from . import views

app_name = 'we_bought_again'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

we_bought_again/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView


class IndexView(TemplateView):
    """トップページ"""
    template_name = 'main/index.html'

we_bought_again/views.py
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView

import os
import environ
from pathlib import Path
from requests_oauthlib import OAuth1Session
import json

BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, '.env'))


class IndexView(TemplateView):
    """トップページ"""
    template_name = 'we_bought_again/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        API_Key = env('API_Key')
        API_Secret_Key = env('API_Secret_Key')
        Access_Token = env('Access_Token')
        Access_Token_Secret = env('Access_Token_Secret')

        data_list = []
        # context = {}
        cnt = 0

        twitter = OAuth1Session(API_Key, API_Secret_Key, Access_Token, Access_Token_Secret)
        search_api = 'https://api.twitter.com/1.1/search/tweets.json'
        oembed_api = 'https://publish.twitter.com/oembed'

        params = {
            # 波ダッシュ、全角チルダ
            'q': '#はぁ〜また買っちゃった OR #はぁ～また買っちゃった -filter:retweets',
            'result_type': 'recent',
            'count': 30,
        }

        print('get res...')
        res = twitter.get(search_api, params=params)
        tweets = json.loads(res.text)

        print('embed...')
        for row in tweets['statuses']:
            cnt += 1
            print(cnt, end='\t')
            try:
                is_media = row['entities']['media']
                name = row['user']['name']
                screen_name = row['user']['screen_name']
                id = row['id']

                oembed_url = f'https://twitter.com/{screen_name}/status/{id}'
                oembed_params = {
                    'url': oembed_url,
                    'align': 'center',
                    'hide_thread': 'true',
                }
                print(screen_name)
                request = twitter.get(oembed_api, params=oembed_params)
                e_data = json.loads(request.text)['html']
                data_list.append(e_data)
                context['e_data'] = data_list
            except KeyError:
                print('pass')
                continue

        return context

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
    <script src="https://kit.fontawesome.com/22f0cfa09f.js" crossorigin="anonymous"></script>
    <title>{% block title %}ダミー{% endblock %}</title>
</head>
<body>
<div class="container-fluid" style="background-color: #fffffc">
    {% block content %}<p>ダミー</p>{% endblock %}
    <div class="container mt-5">
        <p>Copyright © 2021 android-sushi.tech All Rights Reserved.</p>
        <p>Thanks for browsing!</p>
        <a class="btn mb-5" href="{% url 'main:index' %}" role="button">Return to top</a>
    </div>
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</div>
</body>
</html>

templates/main/index.html
{% extends "base.html" %}
{% block title %}welcome!{% endblock %}
{% block content %}

    <div class="container p-1">
        <div class="p-5 my-5 card" style="background-color: #9bf6ff">
            <div class="card-body">
                <h2 class="card-title"><strong>android-sushi.tech</strong></h2>
                <p class="card-text">I'm a beginner in programming.</p>

            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-4 p-1">
                <div class="card" style="background-color:#fdffb6;">
                    <div class="card-body">
                        <h2 class="card-title">Blogs (Tech)</h2>
                        <p class="card-text p-3">coming soon...</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 p-1">
                <div class="card" style="background-color:#bdb2ff;">
                    <div class="card-body">
                        <h2 class="card-title">Blogs (Gadgets)</h2>
                        <a class="btn my-1" href="https://www.gadget-seek.com/" role="button"><i
                                class="fas fa-link fa-fw"></i>Gadget Seek</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 p-1">
                <div class="card" style="background-color:#ffadad;">
                    <div class="card-body">
                        <h2 class="card-title">Apps</h2>
                        <a class="btn my-1" href="{% url 'we_bought_again:index' %}" role="button"><i
                                class="far fa-arrow-alt-circle-right fa-fw"></i>「はぁ～また買っちゃった！」を検索（試作）</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 p-1">
                <div class="card" style="background-color:#caffbf;">
                    <div class="card-body">
                        <h2 class="card-title">Favorites (Website)</h2>
                        <a class="btn my-1" href="https://k-tai.watch.impress.co.jp/" role="button"><i
                                class="fas fa-link fa-fw"></i>K-tai Watch</a>
                        <a class="btn my-1" href="https://www.itmedia.co.jp/mobile/" role="button"><i
                                class="fas fa-link fa-fw"></i>ITmedia Mobile</a>
                        <a class="btn my-1" href="https://ggeek.me/" role="button"><i class="fas fa-link fa-fw"></i>Gadget
                            Geek</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 p-1">
                <div class="card" style="background-color:#ffc6ff;">
                    <div class="card-body">
                        <h2 class="card-title">Favorites (Game)</h2>
                        <a class="btn my-1" href="http://gunvolt.com/en/" role="button"><i
                                class="fas fa-link fa-fw"></i>Azure Striker GUNVOLT</a>
                        <a class="btn my-1" href="http://gunvolt.com/en/X/" role="button"><i
                                class="fas fa-link fa-fw"></i>Luminous Avenger iX</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 p-1">
                <div class="card" style="background-color:#ffd6a5;">
                    <div class="card-body">
                        <h2 class="card-title">Socials</h2>
                        <a class="btn my-1" href="https://twitter.com/android_sushi" role="button"><i
                                class="fab fa-twitter-square fa-fw"></i>Twitter</a>
                        <a class="btn my-1" href="https://github.com/android-sushi" role="button"><i
                                class="fab fa-github fa-fw"></i>GitHub</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/we_bought_again/index.html
{% extends "base.html" %}
{% block title %}「はぁ～また買っちゃった！」を検索{% endblock %}
{% block content %}
    <div class="container p-1">
        <div class="p-5 my-5 card">
            <div class="card-body">
                <h2 class="card-title"><strong>「はぁ～また買っちゃった！」を検索（最新30件）</strong></h2>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            {% for row in e_data %}
                <div class="col-sm-6 col-md-4 col-lg-3">{{ row|safe }}</div>
            {% endfor %}
        </div>
    </div>
{% endblock %}